create table public.users (
  id bigserial not null,
  username character varying(255) not null,
  email text null,
  email_verified_at timestamp without time zone null,
  password character varying(255) not null,
  remember_token character varying(100) null,
  created_at timestamp without time zone null,
  updated_at timestamp without time zone null,
  dni text null,
  telefono text null,
  direccion text null,
  tipo_sangre text null,
  role text null,
  constraint users_pkey primary key (id),
  constraint users_email_unique unique (email)
) TABLESPACE pg_default;


create table public."seriesOT" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  serie text null,
  last_num integer null default 1,
  constraint seriesOT_pkey primary key (id)
) TABLESPACE pg_default;