create table public."seriesOT" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  serie text null,
  last_num integer null default 1,
  constraint seriesOT_pkey primary key (id)
) TABLESPACE pg_default;